import React, { useState } from 'react';
import { X, Copy, Check, Download, FileCode, FileText } from 'lucide-react';
import { ProductDataset } from '../types';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  product: ProductDataset;
  executiveSummary: {
    topStrengths: string[];
    topPainPoints: string[];
    executiveVerdict: string;
    actionableInsights: string[];
  };
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  product,
  executiveSummary,
}) => {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');

  if (!isOpen) return null;

  const analyzed = product.reviews.filter((r) => !!r.analysis);
  const total = analyzed.length || 1;
  const positive = analyzed.filter((r) => r.analysis?.sentiment === 'positive').length;
  const negative = analyzed.filter((r) => r.analysis?.sentiment === 'negative').length;
  const neutral = total - positive - negative;
  const nss = Math.round(((positive - negative) / total) * 100);

  const markdownContent = `# Amazon Product Sentiment Analysis Report (NLP)
**Product:** ${product.title}
**ASIN:** ${product.asin} | **Price:** ${product.price}
**Overall Amazon Rating:** ${product.overallRating}★ (${product.totalReviewsCount.toLocaleString()} ratings)
**Date Generated:** ${new Date().toLocaleDateString()}

---

## 1. Executive Summary & Buyer Verdict
${executiveSummary.executiveVerdict}

## 2. Sentiment Metrics & KPIs
- **Net Sentiment Score (NSS):** ${nss > 0 ? `+${nss}` : nss} / 100
- **Total Analyzed Reviews:** ${analyzed.length}
- **Positive Reviews:** ${positive} (${Math.round((positive / total) * 100)}%)
- **Neutral / Mixed Reviews:** ${neutral} (${Math.round((neutral / total) * 100)}%)
- **Negative Reviews:** ${negative} (${Math.round((negative / total) * 100)}%)

## 3. Top Confirmed Strengths
${executiveSummary.topStrengths.map((s) => `- ${s}`).join('\n')}

## 4. Critical Customer Pain Points & Defects
${executiveSummary.topPainPoints.map((p) => `- ${p}`).join('\n')}

## 5. Strategic Recommendations for Sellers / Brand
${executiveSummary.actionableInsights.map((a, i) => `${i + 1}. ${a}`).join('\n')}

---
*Generated by Amazon Review NLP Sentiment Engine powered by Gemini 3.8 Flash*
`;

  const jsonContent = JSON.stringify(
    {
      product: {
        title: product.title,
        asin: product.asin,
        price: product.price,
        rating: product.overallRating,
      },
      metrics: {
        netSentimentScore: nss,
        totalAnalyzed: total,
        positiveCount: positive,
        negativeCount: negative,
        neutralCount: neutral,
      },
      insights: executiveSummary,
      reviewsSample: product.reviews.map((r) => ({
        id: r.id,
        rating: r.rating,
        title: r.reviewTitle,
        sentiment: r.analysis?.sentiment,
        polarityScore: r.analysis?.score,
        aspects: r.analysis?.aspects,
        isSarcastic: r.analysis?.isSarcastic,
      })),
    },
    null,
    2
  );

  const activeContent = format === 'markdown' ? markdownContent : jsonContent;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([activeContent], {
      type: format === 'markdown' ? 'text/markdown' : 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sentiment-report-${product.asin}.${format === 'markdown' ? 'md' : 'json'}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 backdrop-blur-xs p-4">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-2xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-4 sm:p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-2">
            <span className="font-bold text-slate-900 text-sm sm:text-base">
              Export NLP Sentiment Intelligence Report
            </span>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-200/60"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format toggle & action bar */}
        <div className="px-5 py-3 bg-slate-100/70 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-colors ${
                format === 'markdown'
                  ? 'bg-white shadow-xs text-slate-900'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <FileText className="w-3.5 h-3.5" /> Markdown (.md)
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-semibold transition-colors ${
                format === 'json'
                  ? 'bg-white shadow-xs text-slate-900'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" /> JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 px-3 py-1.5 rounded-md text-xs font-medium bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1 px-3 py-1.5 rounded-md text-xs font-medium bg-amber-500 text-slate-950 font-bold hover:bg-amber-600 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Viewer */}
        <div className="p-4 overflow-y-auto flex-1 bg-slate-950 font-mono text-xs text-slate-200 leading-relaxed">
          <pre className="whitespace-pre-wrap">{activeContent}</pre>
        </div>
      </div>
    </div>
  );
};
